title: Cherie Weren # your name (or website title) here
logo: "/images/Facetune_20-03-2023-14-11-16.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  <a href="https://www.linkedin.com/in/cweren/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal

