title: Cherie Weren # your name (or website title) here
logo: "images/Small Profile Pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Detail oriented and ambitious data analyst specializing in SQL, 
  Microsoft Excel and Tableau with an emphasis on producing and maintaining 
  reports and dashboards. 
  
  My goal is to be a valued member in a collaborative team environment. 
  I am seeking a progressive career opportunity that will utilize and benefit 
  from the unique combination of my previous professional experience and data analysis skills 
  while fostering my ambition to enhance my professional growth through mentorship and continued education. 
  <br><br>
  <a href="https://www.linkedin.com/in/cweren/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal

