title: Cherie Weren # your name (or website title) here
logo: "images/Small Profile Pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Detail oriented and ambitious data analyst specializing in SQL, 
  Microsoft Excel and Tableau with proficiency in Python and R.
  
  Life long learner with a unique combination of previous professional experience and passion for cutting edge methodology.
   
  <br><br>
  <a href="https://www.linkedin.com/in/cweren/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal

